title: ElectroCRUD 2 (beta)
description: Simple solution to manage your database that not involves writing code or installs web-based solutions.
google_analytics: UA-77988987-1
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
